version: "3.9"
services:
  postgres:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "ToDoList"
      POSTGRES_USER: "BogatovVI"
      POSTGRES_PASSWORD: "StartProject"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
  backend:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"